
services: 
  java-app:
    container_name: java_app
    image: crud-java:1.0
    environment:
      - java_db=java_db
    build: .
    ports:
      - 8080:8080
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mariadb:latest
    ports:
      - 3307:3307
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: root
